amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.8
    alpha4: 0.2
    alpha5: 0.1
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::OmniMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: odom
    robot_base_frame: base_link
    odom_topic: /Odometry
    bt_loop_duration: 10
    default_server_timeout: 20
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 30.0
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    controller_plugin_types: ["teb_local_planner::TebLocalPlannerROS"]
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 5.0

    # Goal checker parameters
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 3.14

    FollowPath:
      plugin: teb_local_planner::TebLocalPlannerROS
      teb_autosize: 1.0
      dt_ref: 0.3
      dt_hysteresis: 0.03
      max_samples: 3
      global_plan_overwrite_orientation: True
      allow_init_with_backwards_motion: True
      max_global_plan_lookahead_dist: 0.7
      global_plan_viapoint_sep: 0.2
      global_plan_prune_distance: 1.0
      exact_arc_length: False
      feasibility_check_no_poses: 2
      publish_feedback: True

      # Robot

      max_vel_x: 1.135
      max_vel_x_backwards: 0.5
      max_vel_y: 0.0
      max_vel_theta: 7.0
      acc_lim_x: 9.25
      acc_lim_y: 0.0
      acc_lim_theta: 15.15
      min_turning_radius: 0.0 # omni-drive robot (can turn on place!)
      footprint_model:
        type: "circular"
#        radius: 0.15 # for type "circular"
#        line_start: [ -0.1, 0.0 ] # for type "line" 线模型起始坐标
#        line_end: [ 0.1, 0.0 ] # for type "line" 线模型尾部坐标
#        front_offset: 0.2 # for type "two_circles" 前圆心坐标
#        front_radius: 0.3 # for type "two_circles" 前圆半径
#        rear_offset: 0.2 # for type "two_circles" 后圆心坐标
#        rear_radius: 0.2 # for type "two_circles" 后圆半径
#        vertices: [ [ -0.2,-0.2 ], [ 0.2,-0.2 ], [ 0.2,0.2 ], [ -0.2,0.2 ] ] # for type "polygon" 多边形边界点
        # GoalTolerance

      xy_goal_tolerance: 0.3
      yaw_goal_tolerance: 0.5
      free_goal_vel: False
      complete_global_plan: True

      # Obstacles

      min_obstacle_dist: 0.5 # This value must also include our robot radius, since footprint_model is set to "point".
      inflation_dist: 0.6
      include_costmap_obstacles: True
      costmap_obstacles_behind_robot_dist: 1.0
      obstacle_poses_affected: 15.0
      costmap_converter_plugin: ""
      costmap_converter_spin_thread: True
      costmap_converter_rate: 8
      # Optimization

      no_inner_iterations: 5
      no_outer_iterations: 4
      optimization_activate: True
      optimization_verbose: False
      penalty_epsilon: 0.1
      obstacle_cost_exponent: 4.0
      weight_max_vel_x: 10.0
      weight_max_vel_y: 10.0
      weight_max_vel_theta: 760.0
      weight_acc_lim_x: 100.0
      weight_acc_lim_y: 100.0
      weight_acc_lim_theta: 950.0
      weight_kinematics_nh: 100.0 # WE HAVE A HOLONOMIC ROBOT, JUST ADD A SMALL PENALTY
      weight_kinematics_forward_drive: 200.0
      weight_kinematics_turning_radius: 500.0
      weight_optimaltime: 100.0 # must be > 0
      weight_shortest_path: 0.0
      weight_obstacle: 100.0
      weight_inflation: 0.2
      weight_dynamic_obstacle: 10.0
      weight_dynamic_obstacle_inflation: 0.2
      weight_viapoint: 80.0
      weight_adapt_factor: 2.0


      # Homotopy Class Planner
      enable_homotopy_class_planning: False
      enable_multithreading: True
      max_number_classes: 3
      selection_cost_hysteresis: 1.0
      selection_prefer_initial_plan: 0.95
      selection_obst_cost_scale: 1.0
      selection_alternative_time_cost: False

      roadmap_graph_no_samples: 15
      roadmap_graph_area_width: 5.0
      roadmap_graph_area_length_scale: 1.0
      h_signature_prescaler: 0.5
      h_signature_threshold: 0.1
      obstacle_heading_threshold: 0.45
      switching_blocking_period: 0.0
      viapoints_all_candidates: True
      delete_detours_backwards: True
      max_ratio_detours_duration_best_duration: 3.0
      visualize_hc_graph: False
      visualize_with_time_as_z_axis_scale: 0.0
      # Recovery

      shrink_horizon_backup: True
      shrink_horizon_min_duration: 10.0
      oscillation_recovery: True
      oscillation_v_eps: 0.1
      oscillation_omega_eps: 0.1
      oscillation_recovery_min_duration: 10.0
      oscillation_filter_duration: 10.0

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 20.0
      publish_frequency: 20.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 5
      height: 5
      resolution: 0.02
      robot_radius: 0.2
      plugins: ["voxel2d_layer", "voxel3d_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 8.0
        inflation_radius: 0.7
      voxel2d_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
          raytrace_min_range: 0.0
          raytrace_max_range: 20.0
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      voxel3d_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        mark_threshold: 1
        observation_sources: livox
        min_obstacle_height: 0.00
        max_obstacle_height: 2.0
        livox:
          topic: /segmentation/obstacle
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
          raytrace_min_range: 0.0
          raytrace_max_range: 20.0
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 15.0
      publish_frequency: 15.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      robot_radius: 0.2
      resolution: 0.02
      track_unknown_space: true
      plugins: ["static_layer", "voxel2d_layer", "voxel3d_layer", "inflation_layer"]
      voxel2d_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
          raytrace_min_range: 0.0
          raytrace_max_range: 20.0
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      voxel3d_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        mark_threshold: 1
        observation_sources: livox
        min_obstacle_height: 0.00
        max_obstacle_height: 2.0
        livox:
          topic: /segmentation/obstacle
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
          raytrace_min_range: 0.0
          raytrace_max_range: 20.0
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 8.0
        inflation_radius: 0.7
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 30.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

# planner_server_rclcpp_node:
#   ros__parameters:
#     use_sim_time: False

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 20.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 10.0

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: False
    smoothing_frequency: 15.0
    scale_velocities: False
    feedback: "CLOSED_LOOP"
    max_velocity: [2.5, 2.5, 12.0]
    min_velocity: [-2.5, -2.5, -12.0]
    max_accel: [5.0, 5.0, 15.0]
    max_decel: [-5.0, -5.0, -15.0]
    odom_topic: "Odometry"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0


#    min_vel_x: -0.25
#    min_vel_y: -0.25
#    max_vel_x: 0.25
#    max_vel_y: 0.25
#    max_vel_theta: 7.5
#    min_speed_xy: -0.25
#    max_speed_xy: 0.25
#    min_speed_theta: -7.5
#    acc_lim_x: 0.15
#    acc_lim_y: 0.15
#    acc_lim_theta: 7.5
#    decel_lim_x: -0.15
#    decel_lim_y: -0.15
#    decel_lim_theta: -7.5